-- -------------------------------------------------------------------
-- Add Comprehensive Indian Airports
-- -------------------------------------------------------------------

INSERT IGNORE INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES
('AMD', 'Sardar Vallabhbhai Patel International Airport', 'Ahmedabad', 'India'),
('LKO', 'Chaudhary Charan Singh International Airport', 'Lucknow', 'India'),
('TRV', 'Trivandrum International Airport', 'Thiruvananthapuram', 'India'),
('IXC', 'Chandigarh International Airport', 'Chandigarh', 'India'),
('IXB', 'Bagdogra Airport', 'Bagdogra', 'India'),
('VNS', 'Lal Bahadur Shastri International Airport', 'Varanasi', 'India'),
('ATQ', 'Sri Guru Ram Dass Jee International Airport', 'Amritsar', 'India'),
('BBI', 'Biju Patnaik International Airport', 'Bhubaneswar', 'India'),
('IXJ', 'Jammu Airport', 'Jammu', 'India'),
('SXR', 'Sheikh ul-Alam International Airport', 'Srinagar', 'India'),
('VTZ', 'Visakhapatnam International Airport', 'Visakhapatnam', 'India'),
('NAG', 'Dr. Babasaheb Ambedkar International Airport', 'Nagpur', 'India'),
('PAT', 'Jay Prakash Narayan International Airport', 'Patna', 'India'),
('IXR', 'Birsa Munda Airport', 'Ranchi', 'India'),
('RPR', 'Swami Vivekananda Airport', 'Raipur', 'India'),
('IMF', 'Tulihal International Airport', 'Imphal', 'India'),
('TRZ', 'Tiruchirappalli International Airport', 'Tiruchirappalli', 'India'),
('IXE', 'Mangaluru International Airport', 'Mangalore', 'India'),
('IXZ', 'Vir Savarkar International Airport', 'Port Blair', 'India'),
('IXM', 'Madurai Airport', 'Madurai', 'India'),
('CJB', 'Coimbatore International Airport', 'Coimbatore', 'India'),
('GAU', 'Lokpriya Gopinath Bordoloi International Airport', 'Guwahati', 'India'),
('IDR', 'Devi Ahilya Bai Holkar International Airport', 'Indore', 'India'),
('STV', 'Surat International Airport', 'Surat', 'India'),
('BHO', 'Raja Bhoj Airport', 'Bhopal', 'India'),
('UDR', 'Maharana Pratap Airport', 'Udaipur', 'India'),
('BDQ', 'Vadodara Airport', 'Vadodara', 'India'),
('VGA', 'Vijayawada International Airport', 'Vijayawada', 'India'),
('TPT', 'Tirupati Airport', 'Tirupati', 'India'),
('IXA', 'Maharaja Bir Bikram Airport', 'Agartala', 'India'),
('IXW', 'Sonari Airport', 'Jamshedpur', 'India'),
('MYQ', 'Mandakalli Airport', 'Mysore', 'India'),
('JLR', 'Jabalpur Airport', 'Jabalpur', 'India'),
('IXS', 'Kumbhirgram Airport', 'Silchar', 'India'),
('IXD', 'Prayagraj Airport', 'Allahabad', 'India'),
('GWL', 'Rajmata Vijaya Raje Scindia Air Terminal', 'Gwalior', 'India'),
('DED', 'Jolly Grant Airport', 'Dehradun', 'India'),
('KNU', 'Kanpur Airport', 'Kanpur', 'India'),
('HJR', 'Khajuraho Airport', 'Khajuraho', 'India'),
('DMU', 'Dimapur Airport', 'Dimapur', 'India'),
('AJL', 'Lengpui Airport', 'Aizawl', 'India'),
('SHL', 'Shillong Airport', 'Shillong', 'India');
