-- TripNexus MySQL -> Supabase (PostgreSQL) schema migration.
-- Generated from database/tripnexus_database.sql, database/db.php and migrations/.
-- Run this file in the Supabase SQL Editor for project jtsuchakskithnoohjup.

begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  fullname varchar(100) not null,
  email varchar(100) not null unique,
  password varchar(255) not null,
  phone varchar(20),
  theme varchar(10) default 'light',
  status varchar(20) default 'active',
  is_verified boolean not null default false,
  verification_code varchar(100),
  verification_code_expiry timestamptz,
  email_verified_at timestamptz,
  reset_token varchar(255),
  token_expiry timestamp,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username varchar(50) not null unique,
  email varchar(100) not null unique,
  password varchar(255) not null,
  role varchar(20) default 'superadmin',
  created_at timestamptz not null default now()
);

create table if not exists public.airports (
  airport_code varchar(3) primary key,
  airport_name varchar(100) not null,
  city varchar(50) not null,
  country varchar(50) not null
);

create table if not exists public.airlines (
  airline_id bigint generated by default as identity primary key,
  airline_name varchar(100) not null,
  airline_logo text
);

create table if not exists public.buses (
  bus_id bigint generated by default as identity primary key,
  operator_name varchar(100) not null,
  bus_number varchar(50),
  from_location varchar(100) not null,
  to_location varchar(100) not null,
  departure_time timestamp not null,
  arrival_time timestamp not null,
  price numeric(10,2) not null,
  bus_type varchar(50),
  available_seats integer default 40,
  created_at timestamptz not null default now()
);

create table if not exists public.trains (
  train_id bigint generated by default as identity primary key,
  train_name varchar(100) not null,
  train_number varchar(50) not null,
  from_station varchar(100) not null,
  to_station varchar(100) not null,
  departure_time timestamp not null,
  arrival_time timestamp not null,
  price numeric(10,2) not null,
  available_seats integer default 120,
  created_at timestamptz not null default now()
);

create table if not exists public.hotels (
  hotel_id bigint generated by default as identity primary key,
  name varchar(100) not null,
  city varchar(100) not null,
  address text,
  description text,
  price_per_night numeric(10,2) not null,
  rating numeric(2,1) default 0,
  amenities text,
  main_image text,
  latitude numeric(10,8),
  longitude numeric(11,8),
  created_at timestamptz not null default now()
);

create table if not exists public.hotel_rooms (
  id bigint generated by default as identity primary key,
  hotel_id bigint not null references public.hotels(hotel_id) on delete cascade,
  room_type varchar(50) not null,
  price numeric(10,2) not null,
  available_count integer default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.tour_packages (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  location varchar(100) not null,
  duration integer not null,
  price numeric(10,2) not null,
  description text,
  itinerary text,
  main_image text,
  created_at timestamptz not null default now()
);

create table if not exists public.flights (
  flight_id bigint generated by default as identity primary key,
  flight_number varchar(10) not null unique,
  airline_id bigint references public.airlines(airline_id),
  departure_airport varchar(3) references public.airports(airport_code),
  arrival_airport varchar(3) references public.airports(airport_code),
  departure_time timestamp not null,
  arrival_time timestamp not null,
  base_price numeric(10,2) not null,
  total_seats integer default 60,
  available_seats integer not null,
  status varchar(10) not null default 'scheduled'
    check (status in ('scheduled', 'boarding', 'departed', 'landed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint flights_available_seats_check check (available_seats >= 0)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  booking_type varchar(10) not null
    check (booking_type in ('flight', 'bus', 'train', 'hotel', 'tour')),
  reference_id bigint not null,
  booking_date timestamptz not null default now(),
  status varchar(10) not null default 'pending'
    check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  total_amount numeric(10,2) not null,
  travel_date timestamptz,
  passengers integer default 1
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  amount numeric(10,2) not null,
  payment_method varchar(50) default 'card',
  payment_status varchar(10) not null default 'pending'
    check (payment_status in ('success', 'failed', 'pending', 'refunded')),
  payment_date timestamptz not null default now(),
  transaction_id varchar(100)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  review_type varchar(10) not null
    check (review_type in ('hotel', 'tour', 'flight', 'bus', 'train', 'website')),
  reference_id bigint default 0,
  rating integer check (rating between 1 and 5),
  comment text,
  status varchar(20) default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  type varchar(50) default 'general',
  subject varchar(255) not null,
  message text not null,
  is_read boolean not null default false,
  email_sent_at timestamptz,
  sent_at timestamptz,
  title varchar(100),
  created_at timestamptz not null default now()
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  item_type varchar(10) not null
    check (item_type in ('flight', 'bus', 'train', 'hotel', 'tour')),
  item_id bigint not null,
  item_name varchar(255),
  added_at timestamptz not null default now(),
  constraint wishlist_user_item_unique unique (user_id, item_type, item_id)
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(100) not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token varchar(255) not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tour_schedules (
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tour_packages(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  available_seats integer default 20,
  price numeric(10,2) not null,
  status varchar(10) not null default 'available'
    check (status in ('available', 'full', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.tour_itinerary (
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tour_packages(id) on delete cascade,
  day_number integer not null,
  route_from varchar(100),
  route_to varchar(100),
  transport_type varchar(10) not null default 'None'
    check (transport_type in ('Bus', 'Train', 'Flight', 'None')),
  transport_time time,
  hotel_id bigint references public.hotels(hotel_id) on delete set null,
  activities text,
  created_at timestamptz not null default now()
);

create table if not exists public.train_stations (
  station_code varchar(10) primary key,
  station_name varchar(100) not null,
  city varchar(50) not null,
  state varchar(50)
);

create table if not exists public.bus_locations (
  location_id bigint generated by default as identity primary key,
  city_name varchar(100) not null unique,
  state varchar(50)
);

create table if not exists public.migrations (
  id bigint generated by default as identity primary key,
  migration_name varchar(255) not null unique,
  executed_at timestamptz not null default now()
);

create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists notifications_type_idx on public.notifications(type);
create index if not exists bookings_user_id_idx on public.bookings(user_id);
create index if not exists bookings_status_idx on public.bookings(status);
create index if not exists payments_booking_id_idx on public.payments(booking_id);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists hotel_rooms_hotel_id_idx on public.hotel_rooms(hotel_id);
create index if not exists tour_schedules_tour_id_idx on public.tour_schedules(tour_id);
create index if not exists tour_itinerary_tour_id_idx on public.tour_itinerary(tour_id);

-- Supabase exposes public tables through its API. Enable RLS before connecting a client.
alter table public.users enable row level security;
alter table public.admins enable row level security;
alter table public.airports enable row level security;
alter table public.airlines enable row level security;
alter table public.flights enable row level security;
alter table public.buses enable row level security;
alter table public.trains enable row level security;
alter table public.hotels enable row level security;
alter table public.hotel_rooms enable row level security;
alter table public.tour_packages enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;
alter table public.wishlist enable row level security;
alter table public.contact_messages enable row level security;
alter table public.password_resets enable row level security;
alter table public.tour_schedules enable row level security;
alter table public.tour_itinerary enable row level security;
alter table public.train_stations enable row level security;
alter table public.bus_locations enable row level security;
alter table public.migrations enable row level security;

commit;
